In [1]:
#なるほどね
men=['a','b','c']
women=['d','e','f']
pref={'a':['d','e','f'],'b':['e','d','f'],'c':['d','e','f'],'d':['b','a','c'],'e':['a','b','c'],'f':['a','b','c']}
for n in pref:
        pref[n].reverse()
rank={'d':{'a':2,'b':1,'c':3},'e':{'a':1,'b':2,'c':3},'f':{'a':1,'b':2,'c':3}}
freemen=list(men)
numpart=len(men)
S={}
while freemen:
    m=freemen.pop()
    if len(pref[m])==0:
        continue
    w=pref[m].pop()
    if w not in S:
        S[w]=m
    else:
        mprime=S[w]
        if rank[w][m]<rank[w][mprime]:
            S[w]=m
            freemen.append(mprime)
        else:
            freemen.append(m)
print S

{'e': 'b', 'd': 'a', 'f': 'c'}


In [3]:
list=['a','b']

In [8]:
men.pop()

'c'

In [1]:
#deferred acceptance function
#a　男リスト
#c　preference list
#d　女の男ランク
def da(a,c,d):
    for n in c:
        c[n].reverse()
    freemen=list(a)
    numpart=len(a)
    S={}
    while freemen:
        m=freemen.pop()
        if len(c[m])==0:
            continue
        w=c[m].pop()
        if w not in S:
            S[w]=m
        else:
            mprime=S[w]
            if d[w][m]<d[w][mprime]:
                S[w]=m
                freemen.append(mprime)
            else:
                freemen.append(m)
    print S

In [2]:
a=['a','b','c']
c={'a':['d','e','f'],'b':['e','d','f'],'c':['d','e','f'],'d':['b','a','c'],'e':['a','b','c'],'f':['a','b','c']}
d={'d':{'a':2,'b':1,'c':3},'e':{'a':1,'b':2,'c':3},'f':{'a':1,'b':2,'c':3}}
da(a,c,d)

{'e': 'b', 'd': 'a', 'f': 'c'}


In [ ]:
range(1,3)

In [1]:
#引数をpref（順序付き）と人数
# a={'a':{1:'d',2:'e',3:'f'},'b':{1:'e',2:'d',3:'f'},'c':{1:'d',2:'e',3:'f'}}
#b={'d':{1:'b',2:'a',3:'c'},'e':{1:'a',2:'b',3:'c'},'f':{1:'a',2:'b',3:'c'}}
#c=3
def da2(a,b,c):
    S={}
    free=[]
    for i in a:
        free.append(i)
    n=1
    while free:
        m=free.pop()
        f=a[m][n]
        if f not in S:
            S[f]=m
        else:
            l=S[f]
            for j in range(1,c+1):
                if b[f][j]==m:
                    d=j
                else: continue
            for k in range(1,c+1):
                if b[f][k]==l:
                    e=k
                else: continue
            if e<d:
                free.append(m)
                n+=1
            else:
                S[f]=m
                free.append(l)
                n+=1
        if len(free)==0:
            return S

In [55]:
a={'a':{1:'d',2:'e',3:'f'},'b':{1:'e',2:'d',3:'f'},'c':{1:'d',2:'e',3:'f'}}
b={'d':{1:'b',2:'a',3:'c'},'e':{1:'a',2:'b',3:'c'},'f':{1:'a',2:'b',3:'c'}}

In [3]:
da2(a,b,c)

NameError: name 'c' is not defined

In [56]:
#引数をpref（順序付き）と人数
#男プロポーズと女プロポーズの結果を同時に表示
# a={'a':{1:'d',2:'e',3:'f'},'b':{1:'e',2:'d',3:'f'},'c':{1:'d',2:'e',3:'f'}}
#b={'d':{1:'b',2:'a',3:'c'},'e':{1:'a',2:'b',3:'c'},'f':{1:'a',2:'b',3:'c'}}
#c=3
def da2(a,b):
    S={}
    free=[]
    T={}
    wfree=[]
    for i in a:
        free.append(i)
    for i in b:
        wfree.append(i)
    c=len(free)
    n=1
    while free:
        m=free.pop()
        f=a[m][n]
        if f not in S:
            S[f]=m
        else:
            l=S[f]
            for j in range(1,c+1):
                if b[f][j]==m:
                    d=j
                else: continue
            for k in range(1,c+1):
                if b[f][k]==l:
                    e=k
                else: continue
            if e<d:
                free.append(m)
                n+=1
            else:
                S[f]=m
                free.append(l)
                n+=1
        if len(free)==0: continue
    g=1
    while wfree:
        m=wfree.pop()
        f=b[m][g]
        if f not in T:
            T[f]=m
        else:
            l=T[f]
            for j in range(1,c+1):
                if a[f][j]==m:
                    d=j
                else: continue
            for k in range(1,c+1):
                if a[f][k]==l:
                    e=k
                else: continue
            if e<d:
                wfree.append(m)
                g+=1
            else:
                T[f]=m
                wfree.append(l)
                g+=1
        if len(wfree)==0:
            return S,T

In [57]:
da2(a,b)

({'d': 'a', 'e': 'b', 'f': 'c'}, {'a': 'e', 'b': 'd', 'c': 'f'})

In [17]:
x={1:{'a':'b','c':'d'}}
y={2:{'e':'f'}}

In [19]:
x.update(y)

In [20]:
x

{1: {'a': 'b', 'c': 'd'}, 2: {'e': 'f'}}

In [34]:
a={'x':1,'y':8,'z':2}
b={'x':5,'y':10,'z':7}
c={'x':6,'y':1,'z':10}
d={'x':9,'y':9,'z':10}
e={'x':6,'y':6,'z':2}
f={'x':8,'y':3,'z':4}
g={'x':2,'y':5,'z':5}
h={'x':7,'y':4,'z':8}
i={'x':4,'y':10,'z':6}
j={'x':3,'y':7,'z':9}

In [35]:
x=[]
y=[]
z=[]

In [36]:
w=[a,b,c,d,e,f,g,h,i,j]

In [49]:
S={}
for l in w:
    n=[]
    m=['x','y','z']
    for k in m:
        n.append(l[k])
    o=max(n)
    for p in m:
        if l[p]==o:
            S[str(l)]=p

In [50]:
S

{"{'y': 1, 'x': 6, 'z': 10}": 'z',
 "{'y': 10, 'x': 4, 'z': 6}": 'y',
 "{'y': 10, 'x': 5, 'z': 7}": 'y',
 "{'y': 3, 'x': 8, 'z': 4}": 'x',
 "{'y': 4, 'x': 7, 'z': 8}": 'z',
 "{'y': 5, 'x': 2, 'z': 5}": 'z',
 "{'y': 6, 'x': 6, 'z': 2}": 'y',
 "{'y': 7, 'x': 3, 'z': 9}": 'z',
 "{'y': 8, 'x': 1, 'z': 2}": 'y',
 "{'y': 9, 'x': 9, 'z': 10}": 'z'}

In [1]:
#データ構造は以下のとおり
#ｍ：numberof males
#n:number of females
#maless:[0,1///m-1]
#females:[0,1,///n-1]
#m_pref:二次元配列m*(n+1)
#f_pref:二次元配列n*(m+1)
#m_pref[i]=[0,1,2///n(unmatch)]
#f_prefも同様の順列で表記
#出力は、1次元のm_matched:長さがmのmatch相手を並べた順列
#一回誰かに取られたら-1で置き換える。

In [72]:
import numpy as np
m=np.arange(5)
n=np.arange(8)

In [36]:
m

array([0, 1, 2, 3, 4])

In [42]:
n

array([0, 1, 2, 3, 4, 5, 6, 7])

In [73]:
a=np.random.permutation(9)
b=np.random.permutation(9)
c=np.random.permutation(9)
d=np.random.permutation(9)
e=np.random.permutation(9)

In [74]:
m_pref=np.vstack((a,b,c,d,e))

In [75]:
f=np.random.permutation(6)
g=np.random.permutation(6)
h=np.random.permutation(6)
i=np.random.permutation(6)
j=np.random.permutation(6)
k=np.random.permutation(6)
l=np.random.permutation(6)
o=np.random.permutation(6)

In [76]:
n_pref=np.vstack((f,g,h,i,j,k,l,o))

In [77]:
n_pref

array([[1, 0, 3, 5, 2, 4],
       [3, 2, 5, 0, 4, 1],
       [0, 5, 1, 3, 4, 2],
       [1, 4, 3, 2, 0, 5],
       [2, 0, 1, 4, 3, 5],
       [2, 5, 4, 1, 0, 3],
       [1, 5, 3, 0, 2, 4],
       [4, 5, 0, 3, 2, 1]])

In [78]:
m_pref

array([[2, 3, 1, 7, 5, 8, 6, 0, 4],
       [5, 0, 3, 7, 8, 4, 6, 2, 1],
       [0, 7, 1, 6, 8, 4, 5, 3, 2],
       [4, 7, 5, 0, 3, 8, 6, 2, 1],
       [1, 2, 0, 7, 4, 5, 6, 3, 8]])

In [79]:
#データ形式調整済み。
#女性の選好：n_pref
#男性の選好：m_pref
#男性5人女性8人のマッチング
#unmatchは8で表記
S=[]
n=1
free=range(5)
while free:
    m=free.pop()
    f=m_pref[m,:][n]
    if f not in S:
        S.append(f)
    elif f==8:
        S.append(f)
    else:
        l=S.index(f)
        for j in range(6):
            if n_pref[f,:][j]==m:
                d=j
            else: continue
        for k in range(6):
            if n_pref[f,:][k]==l:
                e=k
            else: continue
        if e<d:
            free.append(m)
            n+=1
        else:
            S.append(m)
            S.pop(l)
            S.insert(l,-1)
            free.append(l)
            n+=1
if len(free)==0:
    print S.reverse()

None
